### PR TITLE
more compatible fetching of handle & support for inventory management screen & performance boost

### PR DESCRIPTION
**Pull request by HotNoob**
Process[] processes = Process.GetProcesses();

removed excess functions, as no longer needed.
---
also made a slight change to for loop to increase performance.... kinda forgot about it.

### CODE REVIEW

**Comment by fabianPas** [comment]
Is this ready for a review / testing now? As you've made a lot of changes.

**Comment by HotNoob** [comment]
ok, good to go! tested. guess i had a few things to clean up :P

**Comment by fabianPas** [comment]
Looking good. Accepted!

**Comment by alchemyapplied** [comment]
hotnoob please speak to kai via youtube or faecbook and tell him where lux is

**Comment by alchemyapplied** [comment]
speak to kai inform him on where lux is

**Comment by fabianPas** [comment]
@alchemyapplied Please refrain from such comments unrelated to the issue.

**Pull request merged**
